import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className="bg-transparent"
        style={{
          background: "radial-gradient(125% 125% at 50% 10%, #ffffff 40%, #14b8a6 100%)",
          minHeight: "100vh"
        }}
      >
        <div className="min-h-screen w-full h-full relative">
          <div className="relative z-10">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
